FROM node:18-alpine

WORKDIR /app 

COPY ./package.json .

RUN npm install


#The  copy is not needed when create a volumes and add reference the dir to the container. But is a good practice to leave it.
COPY . .

CMD ["npm", "run", "start"]

