name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: main
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t jose/frontend -f Dockerfile.dev .
      - run: docker run -e CI=true jose/frontend npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "docker-react web app"
          environment_name: Docker-reactwebapp-env
          existing_bucket_name: elasticbeanstalk-us-east-1-655786143075
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
